query Puestos {
    puesto {
        id
        fechaCreacion
        nivelEstudios
        nombre
        jornada
        turno
        descripcion
        numVacantes
    }
}

query Listas {
    puesto {
        id
        nombre
        jornada
        empresa {
            nombreComercial
            ciudad
        }
        status
        fechaCreacion
    }
}

query Descripcion {
    puesto(filter: { id: { _eq: 2 } }) {
        id
        descripcion
        nivelEstudios
        numVacantes
        turno
    }
}

query filterList {
    puesto(filter: { nombre: { _contains: "M" } }) {
        id
        nombre
        jornada
        empresa {
            nombreComercial
            ciudad
        }
        status
        fechaCreacion
    }
}
mutation FormPage_SubmitFormData(
    $primerNombre: String!
    $otrosNombres: String!
    $apellidoMaterno: String!
    $apellidoPaterno: String!
    $ciudad: String!
    $sexo: String!
    $direccion: String!
    $codigoPostal: String!
    $colonia: String!
    $correo: String
    $telefono: String!
    $fechaNacimiento: Date!
    $puestoId: ID!
) {
    aplicacion: create_aplicacion_item(
        data: {
            primerNombre: $primerNombre
            otrosNombres: $otrosNombres
            apellidoPaterno: $apellidoPaterno
            apellidoMaterno: $apellidoMaterno
            fechaNacimiento: $fechaNacimiento
            ciudad: $ciudad
            codigoPostal: $codigoPostal
            colonia: $colonia
            correo: $correo
            direccion: $direccion
            sexo: $sexo
            telefono: $telefono
            status: "published"
            puesto: { id: $puestoId }
        }
    ) {
        id
    }
}
